services:
  - type: web
    name: lezit-transports-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_GOOGLE_CLIENT_ID
        sync: false 