services:
  # Backend API Service
  - type: web
    name: lezit-transports-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 7d
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USER_BOOKING
        sync: false
      - key: SMTP_PASS_BOOKING
        sync: false
      - key: SMTP_USER_SUPPORT
        sync: false
      - key: SMTP_PASS_SUPPORT
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false

  # Frontend Static Site
  - type: web
    name: lezit-transports-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_GOOGLE_CLIENT_ID
        sync: false 